all_atoms: true
atom_max_neighbors: 8
atom_radius: 5
batch_size: 8
c_alpha_max_neighbors: 24
cache_path: data/cache
config: null
cross_distance_embed_dim: 64
cross_max_distance: 80
cudnn_benchmark: true
data_dir: data/zincbind_cleaned_processed
distance_embed_dim: 64
dropout: 0.1
dynamic_max_cross: true
ema_rate: 0.999
embedding_scale: 1000
embedding_type: sinusoidal
esm_embeddings_path: data/embeddings_output_cleaned
inference_earlystop_goal: max
inference_earlystop_metric: valinf_rmsds_lt2
inference_steps: 20
limit_complexes: 0
log_dir: workdir
lr: 0.001
matching_maxiter: 20
matching_popsize: 20
max_lig_size: null
max_radius: 5.0
n_epochs: 500
no_batch_norm: false
ns: 40
num_conformers: 1
num_conv_layers: 3
num_dataloader_workers: 2
num_inference_complexes: 500
num_workers: 2
nv: 4
pin_memory: false
project: difdock_train
receptor_radius: 15.0
remove_hs: true
restart_dir: null
restart_lr: null
run_name: large_all_atoms_model
scale_by_sigma: true
scheduler: plateau
scheduler_patience: 100
sigma_embed_dim: 64
split_test: data/splits/test_metal3d.txt
split_train: data/splits/train.txt
split_val: data/splits/val.txt
test_sigma_intervals: true
tr_sigma_max: 20.0
tr_sigma_min: 0.1
tr_weight: 1
train_inference_freq: null
use_ema: true
use_second_order_repr: false
val_inference_freq: 20
w_decay: 0.0
wandb: true
